// Public API surface for programmatic use
export { aiTest, beforeAll, afterAll, beforeEach, afterEach, getRegistry, clearRegistry } from './core/registry.js'
export { createTraceHandle, startTraceSession, setCurrentTrace, getCurrentTrace } from './trace-adapter/context.js'
export { registerMatchers } from './matchers/index.js'
export { expect } from './matchers/index.js'
export { runFiles } from './runner.js'
export { reportResults } from './reporter.js'
export { installAIInterceptor, uninstallAIInterceptor } from './interceptors/ai-interceptor.js'
export { startLLMProxy, fetchCapturedTrace } from './proxy/llm-capture.js'
export { recordToolCall } from './tracing.js'
export { safeRecordToolCall, isWorker } from './internals/conditional-recorder.js'
export { resolveMock } from './internals/mock-resolver.js'
export type { TestResult, FileResult, RunnerOptions } from './runner.js'
export type { AITestContext, TraceHandle, LLMStep, ToolCall, CustomStep, TraceStep, RunnerHooks } from './trace-adapter/context.js'
// Workflow capture & replay
export type { WorkflowEvent, WorkflowEventType, WorkflowTrace } from './capture/event.js'
export { TraceRecorder, setCaptureContext, getCaptureContext } from './capture/recorder.js'
export type { CaptureContext } from './capture/recorder.js'
export { ReplayController } from './capture/replay.js'
export { wrapTool } from './interceptors/tool.js'
export { wrapAI } from './interceptors/workflow-ai.js'
export { wrapDB, wrapPgClient, wrapKnex, wrapMongoCollection, wrapRedisClient } from './interceptors/db.js'
export { installDBAutoInterceptor, uninstallDBAutoInterceptor } from './interceptors/db-auto.js'
export { interceptFetch, restoreFetch, readVercelAIStream } from './interceptors/http.js'
export type { VercelAIStreamResult } from './interceptors/http.js'
export { interceptRandom, restoreRandom, interceptDateNow, restoreDateNow } from './interceptors/side-effects.js'
export { runWorkflow } from './workflow-runner.js'
export type { RunWorkflowOptions, WorkflowRunResult } from './workflow-runner.js'
// Agent mid-trace replay
export type { AgentTask, AgentPlan, AgentState, AgentTaskStatus, AgentPlanStatus } from './types/agent.js'
export { serializeAgentState, deserializeAgentState, extractTaskOutputs, resolveTaskInput } from './core/agent-state.js'
